version: "2"
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    links:
      - "sql:database"
    networks:
      app-net:
        ipv4_address: 10.10.0.2
    volumes:
      - ".:/var/www/smartpowerstripe"
    ports:
      - "80:80" aaa

  sql:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    networks:
      app-net:
        ipv4_address: 10.10.0.3
    volumes:
      - "~/projects/docker/data-volumes/sps-mysql:/var/lib/mysql"

networks:
  app-net:
    ipam:
      config:
      - subnet: 10.10.0.0/24
        gateway: 10.10.0.1