- name: Update APT repositories cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - rsync
    - vim
    - mc

- name: Install PIP
  include: pip_install.yml


