- name: Deploy application to develop server
  hosts: develop
  become: true
  vars:
    db_host: localhost
    db_port: 3306
    db_name: smartenergy
    db_username: smartpower
    db_password: smartpower
    ansistrano_deploy_from: "{{ playbook_dir }}/.."
    ansistrano_deploy_to: "/var/www/html"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: rsync
    ansistrano_rsync_set_remote_user: yes
    ansistrano_allow_anonymous_stats: yes
    ansistrano_ensure_shared_paths_exist: no
    ansistrano_after_update_code_tasks_file: "custom/after_update.yml"
    ansistrano_before_symlink_tasks_file: "custom/before_symlink.yml"
  roles:
    - { role: deploy }

- name: Deploy application to develop server
  hosts: test
  become: false
  vars:
    db_host: mysql5
    db_port: 3306
    db_name: raseko_power
    db_username: raseko_power
    db_password: smartpower
    ansistrano_deploy_from: "{{ playbook_dir }}/.."
    ansistrano_deploy_to: "/home/raseko/public_html/test-api.raseko.pl"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: rsync
    ansistrano_rsync_set_remote_user: yes
    ansistrano_allow_anonymous_stats: yes
    ansistrano_ensure_shared_paths_exist: no
    ansistrano_after_update_code_tasks_file: "custom/after_update.yml"
    ansistrano_before_symlink_tasks_file: "custom/before_symlink.yml"
  roles:
    - { role: deploy }