- name: MySQL | Install MySQL server
  apt:
    name: "{{ item }}"
    state: latest
  notify:
    - "Restart MySQL"
  with_items:
    - mysql-server
    - python-dev
    - libmysqlclient-dev

- name: Install the Python MySQL module
  pip:
    name: mysql-python
    state: latest

- name: MySQL | Create "smartenergy" database
  mysql_db:
    name: '{{ db_name }}'
    state: present

- name: MySQL | Remove user
  mysql_user:
    name: '{{ db_user }}'
    state: absent

- name: MySQL | Create smartpower user
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_pass }}'
    host: '%'
    priv: '{{ db_name }}.*:ALL'
    state: present

- name: MySQL | Update MySQL configuration
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify:
    - "Restart MySQL"